//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOGLAR
    {
        public int BLOGID { get; set; }
        public string BLOGAD { get; set; }
        public string BLOGIMG_1 { get; set; }
        public string BLOGIMG_2 { get; set; }
        public string BLOGIMG_3 { get; set; }
        public string BLOGLOGO { get; set; }
        public string BLOGYAZI { get; set; }
        public Nullable<int> UYEID { get; set; }
        public Nullable<int> KATEID { get; set; }
        public string BLOGKUCUKYAZI { get; set; }
    
        public virtual KATEGORILER KATEGORILER { get; set; }
        public virtual UYELER UYELER { get; set; }
    }
}
