//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESAJLAR
    {
        public int CONID { get; set; }
        public string CONMAIL { get; set; }
        public string CONADSOYAD { get; set; }
        public string CONICERIK { get; set; }
    }
}
